.TH install\-language\-locales 8 "January 24, 2005" "Martin Pitt"

.SH NAME
install\-language\-locales \- generate all supported locales for a
given language

.SH SYNOPSIS

.B install\-language\-locales 
.I language-code

.SH DESCRIPTION
This script installs all UTF-8 locales which use the supplied language
code. However, locales ending with
.B @euro
are ignored since these are deprecated.

.SH SEE ALSO
.BR remove\-language\-locales (8),
.BR locale-gen (8)

.SH AUTHOR
.B install\-language\-locales 
was written by Martin Pitt <martin.pitt@ubuntu.com>. 

