.TH remove\-language\-locales 8 "January 24, 2005" "Martin Pitt"

.SH NAME
remove\-language\-locales \- remove all installed locales for a
given language

.SH SYNOPSIS

.B remove\-language\-locales 
.I language-code

.SH DESCRIPTION
This script removes all installed locales which use the supplied
language code, thus reversing the effect of 
.B install\-language\-locales

.SH SEE ALSO
.BR install\-language\-locales (8),
.BR locale-gen (8)

.SH AUTHOR
.B remove\-language\-locales 
was written by Martin Pitt <martin.pitt@ubuntu.com>. 

